<?php

namespace App\Exceptions;

use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Auth\AuthenticationException;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Throwable;

class Handler extends ExceptionHandler
{
    /**
     * A list of the exception types that are not reported.
     *
     * @var array<int, class-string<Throwable>>
     */
    protected $dontReport = [
        //
    ];

    /**
     * A list of the inputs that are never flashed for validation exceptions.
     *
     * @var array<int, string>
     */
    protected $dontFlash = [
        'current_password',
        'password',
        'password_confirmation',
    ];

    /**
     * Register the exception handling callbacks for the application.
     *
     * @return void
     */
    public function register()
    {
        $this->reportable(function (Throwable $e) {
            //
        });
    }

    public function render($request, Throwable $e)
    {
        $customized = false;
        if ($e instanceof AuthorizationException) {
            $msg = 'Unauthorized, you cannot access this route';
            $statusCode = Response::HTTP_UNAUTHORIZED;
            $customized = true;
        } else if ($e instanceof AuthenticationException) {
            $msg = 'Unauthenticated, first you should login';
            $statusCode = Response::HTTP_UNAUTHORIZED;
            $customized = true;
        } else if ($e instanceof ModelNotFoundException) {
            $msg = 'Not found';
            $statusCode = Response::HTTP_NOT_FOUND;
            $customized = true;
        } else if ($e instanceof NotFoundHttpException) {
            $msg = 'Not found';
            $statusCode = Response::HTTP_NOT_FOUND;
            $customized = true;
        }

        if ($customized && $request->expectsJson()) {
            return new JsonResponse([
                "message" => $msg,
                'success' => false,
            ], $statusCode);
        }
        return parent::render($request, $e); // TODO: Change the autogenerated stub
    }
}
